In [7]:
from __future__ import division

import numpy as np
from dipy.core.gradients import gradient_table
import dipy.reconst.shm as shm
import nibabel as nib
from dipy.data.fetcher import read_bvals_bvecs
import scipy.io
import scipy
import numpy
from sklearn.ensemble import RandomForestRegressor
from sklearn import linear_model
import matplotlib.pyplot as plt
import pandas
from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasRegressor
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import RobustScaler, MinMaxScaler
from sklearn.pipeline import Pipeline
from keras import optimizers
from keras.initializers import RandomUniform
from sklearn.decomposition import PCA, KernelPCA
from keras.layers import Dropout

In [8]:
def sh_fit_adc(data, mask, bvals, bvecs, order, regularise=0.006, \
                is_mrtrix=True, flipX=False, flipY=False, flipZ=False, scale=1):
    """
    Spherical Harmonic fit to the normalised signal E.

    Returns:
        shimg: SH fit image # because Camino fits the ADC
    """
    print ('Estimating ADC in SH basis...')
    gtab = gradient_table(bvals, bvecs, b0_threshold=24)
    Esig = shm.normalize_data(data, gtab.b0s_mask)
    Sind = np.where(gtab.b0s_mask==False)[0]
    b = gtab.bvals[Sind]
    g = gtab.gradients[Sind, :]
    if flipX:
        g[:, 0] = -g[:, 0]
    if flipY:
        g[:, 1] = -g[:, 1]
    if flipZ:
        g[:, 2] = -g[:, 2]
    r, th, ph = shm.cart2sphere(g[:,0], g[:,1], g[:,2])
    if is_mrtrix:
        print("SH basis: mrtrix")
        B, m, n = shm.real_sym_sh_mrtrix(order, th, ph)
        print(m)
        print(n)
    else:
        print("SH basis: dipy")
        B, m, n = shm.real_sym_sh_basis(order, th, ph)

    L = n*n*(n+1)*(n+1) * regularise
    Binv = shm.smooth_pinv(B, L)

    shimg = np.zeros((mask.shape[0], mask.shape[1], mask.shape[2], B.shape[1]), \
            dtype=float)
    mindx = np.argwhere(mask>0)
    for i, j, k in mindx:
        E = -np.log(Esig[i, j, k, Sind]) * 1/b
        shimg[i, j, k, :] = np.matmul(Binv, E)

    return shimg*scale

In [9]:
def convert_to_camino(df):
    output = pandas.DataFrame()
    output[0] = 0 # exit
    output[1] = 0
    output[2] = df[0] # c00
    output[3] = df[3]
    output[4] = df[2] 
    output[5] = df[4]
    output[6] = df[1]
    output[7] = df[5]
    output[8] = df[10]
    output[9] = df[9]
    output[10] = df[11]
    output[11] = df[8]
    output[12] = df[12]
    output[13] = df[7]
    output[14] = df[13]
    output[15] = df[6]
    output[16] = df[14]
    output[0] = 0
    output[1] = 0
    return output

In [10]:
# Create mask for training database
mask = np.ones((10929,1,1))
print(mask.shape)

for s in range(1,36):
    
    
    print('shell ' + str(s))
    
    # Load bvals and bvec files
    bvals, bvecs = read_bvals_bvecs('shell_' + str(s) + '.bvals', 'shell_' + str(s) + '.bvecs')
    
    # Load training DB NF signals per shell
    data = scipy.io.loadmat('Signals_NF_shell' + str(s) + '.mat')
    shell = data['shell']
    shell = np.expand_dims(shell, axis = 1)
    shell = np.expand_dims(shell, axis = 1)

    # call the function that fits the spherical harmonics
    shimg = sh_fit_adc(shell, mask, bvals, bvecs, 4, is_mrtrix = True)
    shimg = np.squeeze(shimg)
    
    # convert into camino units
    shimg = shimg * 1e-6

    # save the fit
    data = {}
    data['shimg_R0_006_S1'] = (convert_to_camino(pandas.DataFrame(shimg))).as_matrix()
    scipy.io.savemat('signals_shimg_shell' + str(s) +'_R0_006_S1.mat',data)


(10929, 1, 1)
shell 1
Estimating ADC in SH basis...
SH basis: mrtrix
[ 0  2  1  0 -1 -2  4  3  2  1  0 -1 -2 -3 -4]
[0 2 2 2 2 2 4 4 4 4 4 4 4 4 4]
shell 2
Estimating ADC in SH basis...
SH basis: mrtrix
[ 0  2  1  0 -1 -2  4  3  2  1  0 -1 -2 -3 -4]
[0 2 2 2 2 2 4 4 4 4 4 4 4 4 4]
shell 3
Estimating ADC in SH basis...
SH basis: mrtrix
[ 0  2  1  0 -1 -2  4  3  2  1  0 -1 -2 -3 -4]
[0 2 2 2 2 2 4 4 4 4 4 4 4 4 4]
shell 4
Estimating ADC in SH basis...
SH basis: mrtrix
[ 0  2  1  0 -1 -2  4  3  2  1  0 -1 -2 -3 -4]
[0 2 2 2 2 2 4 4 4 4 4 4 4 4 4]
shell 5
Estimating ADC in SH basis...
SH basis: mrtrix
[ 0  2  1  0 -1 -2  4  3  2  1  0 -1 -2 -3 -4]
[0 2 2 2 2 2 4 4 4 4 4 4 4 4 4]
shell 6
Estimating ADC in SH basis...
SH basis: mrtrix
[ 0  2  1  0 -1 -2  4  3  2  1  0 -1 -2 -3 -4]
[0 2 2 2 2 2 4 4 4 4 4 4 4 4 4]
shell 7
Estimating ADC in SH basis...
SH basis: mrtrix
[ 0  2  1  0 -1 -2  4  3  2  1  0 -1 -2 -3 -4]
[0 2 2 2 2 2 4 4 4 4 4 4 4 4 4]
shell 8
Estimating ADC in SH basis...
SH basis: 

In [11]:
shell = scipy.io.loadmat('signals_shimg_shell1_R0_006_S1.mat')
shell = pandas.DataFrame(shell['shimg_R0_006_S1'])
print(shell)

        0    1             2             3             4             5   \
0      0.0  0.0  4.142238e-09  1.421184e-09  5.673825e-12  4.515276e-12   
1      0.0  0.0  4.048756e-09  1.411367e-09 -9.668507e-12 -5.666505e-12   
2      0.0  0.0  2.670240e-09  9.122979e-10 -1.095429e-12 -2.764851e-12   
3      0.0  0.0  1.932207e-09  6.470675e-10 -3.377105e-12 -8.741951e-12   
4      0.0  0.0  2.746550e-09  9.260697e-10 -5.755862e-12  2.596017e-12   
5      0.0  0.0  4.159418e-09  1.438084e-09 -5.540238e-12  3.585636e-12   
6      0.0  0.0  4.030248e-09  1.383951e-09  8.052746e-12  1.866467e-12   
7      0.0  0.0  2.666229e-09  9.038272e-10  4.539040e-12 -6.757815e-12   
8      0.0  0.0  1.928482e-09  6.398064e-10  2.154235e-12  2.016302e-12   
9      0.0  0.0  2.760335e-09  9.359413e-10  6.656719e-12  5.228014e-12   
10     0.0  0.0  4.158524e-09  1.430727e-09 -6.143888e-12 -9.538391e-12   
11     0.0  0.0  4.062735e-09  1.387872e-09  4.419070e-12  8.221613e-12   
12     0.0  0.0  2.683103

In [12]:
shell

0    1             2             3             4             5   \
0      0.0  0.0  4.142238e-09  1.421184e-09  5.673825e-12  4.515276e-12   
1      0.0  0.0  4.048756e-09  1.411367e-09 -9.668507e-12 -5.666505e-12   
2      0.0  0.0  2.670240e-09  9.122979e-10 -1.095429e-12 -2.764851e-12   
3      0.0  0.0  1.932207e-09  6.470675e-10 -3.377105e-12 -8.741951e-12   
4      0.0  0.0  2.746550e-09  9.260697e-10 -5.755862e-12  2.596017e-12   
5      0.0  0.0  4.159418e-09  1.438084e-09 -5.540238e-12  3.585636e-12   
6      0.0  0.0  4.030248e-09  1.383951e-09  8.052746e-12  1.866467e-12   
7      0.0  0.0  2.666229e-09  9.038272e-10  4.539040e-12 -6.757815e-12   
8      0.0  0.0  1.928482e-09  6.398064e-10  2.154235e-12  2.016302e-12   
9      0.0  0.0  2.760335e-09  9.359413e-10  6.656719e-12  5.228014e-12   
10     0.0  0.0  4.158524e-09  1.430727e-09 -6.143888e-12 -9.538391e-12   
11     0.0  0.0  4.062735e-09  1.387872e-09  4.419070e-12  8.221613e-12   
12     0.0  0.0  2.683103e-09  9.120349e-10 -1.267790e-11 -1.859844e-12   
13     0.0  0.0  1.938117e-09  6.435511e-10  3.505678e-15  7.828660e-13   
14     0.0  0.0  2.763876e-09  9.430606e-10 -1.103441e-11  2.829462e-12   
15     0.0  0.0  4.153177e-09  1.432323e-09 -1.395638e-11 -9.575756e-12   
16     0.0  0.0  4.052191e-09  1.401111e-09 -5.056365e-12 -4.607754e-12   
17     0.0  0.0  2.662341e-09  8.968509e-10  4.212148e-12 -1.172051e-12   
18     0.0  0.0  1.928170e-09  6.457236e-10 -9.092238e-12  7.639655e-12   
19     0.0  0.0  2.758308e-09  9.371662e-10  3.445253e-12  9.156269e-15   
20     0.0  0.0  4.150741e-09  1.428986e-09 -2.518414e-12 -1.568392e-11   
21     0.0  0.0  4.056297e-09  1.404494e-09 -4.084424e-12 -9.979620e-12   
22     0.0  0.0  2.654377e-09  9.050500e-10  1.005305e-11 -5.991982e-12   
23     0.0  0.0  1.928846e-09  6.423508e-10 -1.831596e-13 -5.643806e-12   
24     0.0  0.0  2.770683e-09  9.462094e-10 -1.684795e-11  1.444625e-12   
25     0.0  0.0  3.306610e-09  1.800460e-09  4.042893e-12 -5.151542e-12   
26     0.0  0.0  3.215060e-09  1.740972e-09  2.787027e-12 -1.181920e-12   
27     0.0  0.0  2.124976e-09  1.134445e-09  2.571028e-12  2.824740e-12   
28     0.0  0.0  1.544605e-09  8.143371e-10 -2.833540e-12  1.816933e-12   
29     0.0  0.0  2.207080e-09  1.180066e-09  2.669169e-12 -2.771615e-12   
...    ...  ...           ...           ...           ...           ...   
10899  0.0  0.0  3.450921e-09  1.597599e-09  1.132235e-11  7.697127e-12   
10900  0.0  0.0  3.047809e-09  1.404521e-09  2.583669e-12 -4.282339e-12   
10901  0.0  0.0  1.890651e-09  8.413665e-10 -4.157621e-12 -9.267088e-13   
10902  0.0  0.0  1.849500e-09  8.135340e-10 -4.006368e-12 -7.194097e-12   
10903  0.0  0.0  1.770076e-09  7.795005e-10  4.420945e-12  5.900991e-12   
10904  0.0  0.0  2.984062e-09  1.813889e-09 -1.087561e-11 -4.381090e-12   
10905  0.0  0.0  2.641489e-09  1.593263e-09 -1.131828e-11  5.606953e-12   
10906  0.0  0.0  1.640008e-09  9.529788e-10 -4.894777e-12  3.653672e-12   
10907  0.0  0.0  1.603828e-09  9.317446e-10 -8.929982e-13 -1.067553e-12   
10908  0.0  0.0  1.527647e-09  8.808742e-10 -9.430942e-13 -5.858655e-12   
10909  0.0  0.0  3.000812e-09  1.832380e-09 -7.226801e-13 -3.655017e-12   
10910  0.0  0.0  2.651833e-09  1.608052e-09  3.791034e-12 -9.674510e-12   
10911  0.0  0.0  1.640005e-09  9.526773e-10  2.193166e-12  1.492949e-12   
10912  0.0  0.0  1.605630e-09  9.333948e-10  2.654384e-12 -1.004888e-12   
10913  0.0  0.0  1.534041e-09  8.895714e-10 -4.048663e-12  2.267428e-12   
10914  0.0  0.0  3.009805e-09  1.819731e-09 -5.528173e-12  2.416099e-12   
10915  0.0  0.0  2.652189e-09  1.588609e-09 -3.626535e-12  6.842053e-12   
10916  0.0  0.0  1.638609e-09  9.451702e-10  1.828885e-12  2.879426e-12   
10917  0.0  0.0  1.606857e-09  9.312018e-10 -4.350803e-13  1.919354e-12   
10918  0.0  0.0  1.544255e-09  8.897657e-10 -6.519079e-12 -1.090106e-12   
10919  0.0  0.0  2.976479e-09  1.822916e-09  3.106179e-12 -4.369325e-12   
10920  0.0  0.0  2.641384e-09  1.